### ISSUE TITLE
sample project not functioning windows

### ISSUE THREAD

**Issue by SushilRagoonath** [EvilPudding/candle#8]
I compile the sample project using build.bat ,I then start it and it shows an editor briefly before crashing.Here is the console output 

no loader plane
no loader round_quad
no loader sky
no loader venus
Window created
GL Vendor : NVIDIA Corporation
GL Renderer : GeForce GTX 1050 Ti/PCIe/SSE2
GL Version (string) : 4.3.0 NVIDIA 451.67
GLSL Version : 4.30 NVIDIA via Cg compiler
0
1
0
0
0
vs ready candle:quad
fetching candle:quad.glsl
fetching candle:gbuffer#0.glsl
fetching candle:query_mips#0.glsl
fetching candle:depth#0.glsl
fetching candle:select#0.glsl
fetching candle:transparent#0.glsl
fetching candle:gbuffer#1.glsl
fetching candle:query_mips#1.glsl
fetching candle:depth#1.glsl
fetching candle:select#1.glsl
fetching candle:transparent#1.glsl
fetching candle:gbuffer#2.glsl
fetching candle:query_mips#2.glsl
fetching candle:depth#2.glsl
fetching candle:select#2.glsl
fetching candle:transparent#2.glsl
fetching candle:gbuffer#3.glsl
fetching candle:query_mips#3.glsl
fetching candle:depth#3.glsl
fetching candle:select#3.glsl
fetching candle:transparent#3.glsl
floor.obj counts 0 0 0 0
                end object floor.obj
loading tile.mat
cloth.obj counts 0 0 0 0
                end object cloth.obj
'ailed to fetch texture 'tile_diffuse
vs ready model
shader 27 ready f:candle:query_mips#0 v:model 1
fetching candle:framebuffer_draw.glsl

**Comment by EvilPudding** [comment]
Thanks for reporting. This is the twinpeaks project? Could you check if you can find `tile_diffuse.tga` file in `candle/build/data.zip`?

**Comment by SushilRagoonath** [comment]
it is there under the tile folder.

**Comment by EvilPudding** [comment]
Can you try to run the exe in debug mode? If you have Visual Studio installed, to know where it's halting? I assume it's the fact it's not being able to find the tile diffuse texture, but I don't know why that would happen...

**Comment by SushilRagoonath** [comment]
Okay I will let you know what happens

**Comment by SushilRagoonath** [comment]
How can I compile the exe with symbols enabled because I cannot understand anything in assembly when debugging in VS

**Comment by SushilRagoonath** [comment]
okay I seperated some of operations and got something,hopefully it helps.
![debug](https://user-images.githubusercontent.com/48589447/97060697-752a9480-1594-11eb-9d26-1b6e8c10bff9.PNG)

**Comment by EvilPudding** [comment]
Damn, don't do that, that's way too much work.

You could just try to add the debug flag on the `cl` command in both `build.bat` I thought they were already enabled, but it seems I was wrong... Right now I'm not on the windows machine I sometimes compile as debug, If you can't figure out how to add the flags, or you don't think it's worth it, tomorrow I may go into it in more detail.

Thanks for taking the time.

**Comment by EvilPudding** [comment]
If you update with `git pull origin master` and `git submodule update` and remove `candle\build` and `build`, does it still happen?

**Comment by SushilRagoonath** [comment]
yup still there,updated the submodule and twinpeaks.
GL Vendor : NVIDIA Corporation
GL Renderer : GeForce GTX 1050 Ti/PCIe/SSE2
GL Version (string) : 4.3.0 NVIDIA 451.67
GLSL Version : 4.30 NVIDIA via Cg compiler
floor.obj counts 0 0 0 0
                end object floor.obj
loading tile.mat
cloth.obj counts 0 0 0 0
                end object cloth.obj
'ailed to fetch texture 'tile_diffuse
Segmentation fault

**Comment by SushilRagoonath** [comment]
So I cant even link the resources using the alternate method by changing the candle.c file and the build.bat ,I get
OSpooky!

on runtime

**Comment by EvilPudding** [comment]
What do you mean by "changing the candle.c file"? What are you changing?

**Comment by SushilRagoonath** [comment]
// #ifndef __EMSCRIPTEN__
// 	if (get_archive(&sauces_bytes, &sauces_size))
// 	{
// 		c_sauces_me_a_zip(c_sauces(&SYS), sauces_bytes, sauces_size);
// 	}
// #else
	c_sauces_index_dir(c_sauces(&SYS), "resauces");
// #endif

just changed it to always use the file directory

**Comment by SushilRagoonath** [comment]
Sorry to add more, I'm now trying on my laptop and after updating the submodules and everything im getting:
GL Vendor : Intel
GL Renderer : Intel(R) UHD Graphics 620
GL Version (string) : 4.3.0 - Build 24.20.100.6286
GLSL Version : 4.30 - Build 24.20.100.6286
Log found for 'candle:quad':
ERROR: 0:304: '' : illegal recursive expansion of macro camera
ERROR: 0:304: 'camera' : failed to expand macro
ERROR: 0:345: '' : illegal recursive expansion of macro camera
ERROR: 0:345: 'camera' : failed to expand macro
ERROR: 0:467: '' : illegal recursive expansion of macro camera
ERROR: 0:467: 'camera' : failed to expand macro
ERROR: 0:468: '' : illegal recursive expansion of macro camera
ERROR: 0:468: 'camera' : failed to expand macro
ERROR: 0:469: '' : illegal recursive expansion of macro camera
ERROR: 0:469: 'camera' : failed to expand macro

candle:quad

does this mean the files are loading correctly here atleast?

**Comment by EvilPudding** [comment]
I tried reproducing it and can't seem to be able to... The `camera' : failed to expand macro` seems to be driver specific, but I thin I fixed it. Not sure how well it will run on an Intel chip. As to on the nvidia one, could you follow these steps specifically?
`cd twinpeaks`
`rmdir build`
`cd candle`
`git pull origin master`
`rmdir build`
`cd ..`
`build.bat`

**Comment by SushilRagoonath** [comment]
Camera seems fine now on nvidia, Also what platform are you runnning on?

**Comment by milen-prg** [comment]
After successful compilation, the Sample project (main.exe) still crashes on Windows 10 Pro 64bit - April 2023

**Comment by lorenzocampanile** [comment]
Same

.exe output:
```
GL Vendor : NVIDIA Corporation
GL Renderer : NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2
GL Version (string) : 4.3.0 NVIDIA 546.29
GLSL Version : 4.30 NVIDIA via Cg compiler
floor.obj counts 0 0 0 0
                end object floor.obj
loading tile.mat
cloth.obj counts 0 0 0 0
                end object cloth.obj
'ailed to fetch texture 'tile_diffuse
```

**Comment by EvilPudding** [comment]
It's been a long time since I've picked this project up, and I don't currently have a windows set up so it would be hard for me to debug this issue. If you want to investigate / look into it feel free to do so.

Perhaps I should tag this project as not currently in development until I have spare time to solve these issues.

I love this project and eventually want to clean it up/improve/simplify it. Perhaps next month or beginning of next year.

Sorry for the inconvenience.
